version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: R@d!0252
      POSTGRES_USER: postgres
      POSTGRES_DB: post_info
    volumes:
      - //c/postgres_container_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: radolina/post_service_img:latest
    container_name: post_service_container
#    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/post_info
    depends_on:
      - db

