version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: post_info
    volumes:
      - postgres_container_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: post_service:latest
    container_name: post_service_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.2:5432/post_info
    depends_on:
      - db

volumes:
  postgres_container_data:
