on:
  push:
    paths:
      - "{{SERVICE_NAME}}/**"
      - ".github/workflows/{{SERVICE_NAME}}.yaml"


jobs:
  build_{{SERVICE_NAME}}:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file {{SERVICE_NAME}}/pom.xml

  test_{{SERVICE_NAME}}:
    needs: build_{{SERVICE_NAME}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test --file {{SERVICE_NAME}}/pom.xml
