services:
  db:
    ports:
      - 5432:5432
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: R@d!0252
      POSTGRES_USER: postgres
      POSTGRES_DB: post_info
    volumes:
      - //c/postgres_container_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: radolina/post_service_img:latest
    container_name: post_service_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/post_info
    depends_on:
      - db

