name: Auth_service CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - 'account_service/**'
jobs:

  build_auth_service:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file account_service/pom.xml

  test_auth_service:
    needs: build_auth_service
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test --file account_service/pom.xml