on:
  push:
    paths:
      - "auths_service/**"
      - ".github/workflows/auths_service.yml"
      - "docker-compose.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Upgrade pip and install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Create requirements.txt
        run: |
          pip freeze > requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  docker:
    needs: build
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Build Docker image
        run: |
          cd auths_service
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/auths_service_img:latest .
      - name: Push Docker image to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auths_service_img:latest
      - name: Run Docker Compose
        run: |
          docker-compose up -d
          docker ps