name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_post_service:
    if: ${{ github.event_name == 'push' && contains(github.event.commits.*.added, './post_service') || contains(github.event.commits.*.modified, './post_service') }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./post_service
  build_auth_service:
    if: ${{ github.event_name == 'push' && contains(github.event.commits.*.added, './authentication_service') || contains(github.event.commits.*.modified, './authentication_service') }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./authentication_service



