name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - post_service
          - account_service
          # Add more service directories as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check for changes and build/test with Maven
        run: |
          for service_dir in "${{ matrix.dir }}"; do
            echo "Checking for changes in ${service_dir}"
            if ! git log -- "${service_dir}" &> /dev/null; then
              echo "No commits found in ${service_dir}, proceeding with build and test"
              cd "${service_dir}" || exit 1
              mvn clean install
              mvn test
              cd ..
            else
              echo "Changes detected in ${service_dir}"
              cd "${service_dir}" || exit 1
              mvn clean install
              mvn test
              cd ..
            fi
          done  
