name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - 'post_service/**'
jobs:
  build_post_service:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: Build with Maven
        run: mvn -B package --file post_service/pom.xml

  test_post_service:
    needs: build_post_service
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: Test with Maven
        run: mvn test --file post_service/pom.xml

#  build_auth_service:
#    if: contains(github.event.head_commit.modified, 'authentication_service/')
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#      - name: Build with Maven
#        run: mvn -B package --file authentication_service/pom.xml
#
#  test_auth_service:
#    needs: build_auth_service
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#      - name: Test with Maven
#        run: mvn test --file authentication_service/pom.xml
